// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/binance/market.proto

package api_binance

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBinanceMarketDepthRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBinanceMarketDepthRequest) Reset()         { *m = GetBinanceMarketDepthRequest{} }
func (m *GetBinanceMarketDepthRequest) String() string { return proto.CompactTextString(m) }
func (*GetBinanceMarketDepthRequest) ProtoMessage()    {}
func (*GetBinanceMarketDepthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec8c46fab743ea33, []int{0}
}

func (m *GetBinanceMarketDepthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBinanceMarketDepthRequest.Unmarshal(m, b)
}
func (m *GetBinanceMarketDepthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBinanceMarketDepthRequest.Marshal(b, m, deterministic)
}
func (m *GetBinanceMarketDepthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBinanceMarketDepthRequest.Merge(m, src)
}
func (m *GetBinanceMarketDepthRequest) XXX_Size() int {
	return xxx_messageInfo_GetBinanceMarketDepthRequest.Size(m)
}
func (m *GetBinanceMarketDepthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBinanceMarketDepthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBinanceMarketDepthRequest proto.InternalMessageInfo

func (m *GetBinanceMarketDepthRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetBinanceMarketDepthRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Asks struct {
	Low                  string   `protobuf:"bytes,1,opt,name=Low,proto3" json:"Low,omitempty"`
	High                 string   `protobuf:"bytes,2,opt,name=High,proto3" json:"High,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asks) Reset()         { *m = Asks{} }
func (m *Asks) String() string { return proto.CompactTextString(m) }
func (*Asks) ProtoMessage()    {}
func (*Asks) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec8c46fab743ea33, []int{1}
}

func (m *Asks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asks.Unmarshal(m, b)
}
func (m *Asks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asks.Marshal(b, m, deterministic)
}
func (m *Asks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asks.Merge(m, src)
}
func (m *Asks) XXX_Size() int {
	return xxx_messageInfo_Asks.Size(m)
}
func (m *Asks) XXX_DiscardUnknown() {
	xxx_messageInfo_Asks.DiscardUnknown(m)
}

var xxx_messageInfo_Asks proto.InternalMessageInfo

func (m *Asks) GetLow() string {
	if m != nil {
		return m.Low
	}
	return ""
}

func (m *Asks) GetHigh() string {
	if m != nil {
		return m.High
	}
	return ""
}

type Bids struct {
	Low                  string   `protobuf:"bytes,1,opt,name=Low,proto3" json:"Low,omitempty"`
	High                 string   `protobuf:"bytes,2,opt,name=High,proto3" json:"High,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bids) Reset()         { *m = Bids{} }
func (m *Bids) String() string { return proto.CompactTextString(m) }
func (*Bids) ProtoMessage()    {}
func (*Bids) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec8c46fab743ea33, []int{2}
}

func (m *Bids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bids.Unmarshal(m, b)
}
func (m *Bids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bids.Marshal(b, m, deterministic)
}
func (m *Bids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bids.Merge(m, src)
}
func (m *Bids) XXX_Size() int {
	return xxx_messageInfo_Bids.Size(m)
}
func (m *Bids) XXX_DiscardUnknown() {
	xxx_messageInfo_Bids.DiscardUnknown(m)
}

var xxx_messageInfo_Bids proto.InternalMessageInfo

func (m *Bids) GetLow() string {
	if m != nil {
		return m.Low
	}
	return ""
}

func (m *Bids) GetHigh() string {
	if m != nil {
		return m.High
	}
	return ""
}

type GetBinanceMarketDepthResponse struct {
	LastUpdateId         int32    `protobuf:"varint,1,opt,name=lastUpdateId,proto3" json:"lastUpdateId,omitempty"`
	Bids                 []*Bids  `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks                 []*Asks  `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBinanceMarketDepthResponse) Reset()         { *m = GetBinanceMarketDepthResponse{} }
func (m *GetBinanceMarketDepthResponse) String() string { return proto.CompactTextString(m) }
func (*GetBinanceMarketDepthResponse) ProtoMessage()    {}
func (*GetBinanceMarketDepthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec8c46fab743ea33, []int{3}
}

func (m *GetBinanceMarketDepthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBinanceMarketDepthResponse.Unmarshal(m, b)
}
func (m *GetBinanceMarketDepthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBinanceMarketDepthResponse.Marshal(b, m, deterministic)
}
func (m *GetBinanceMarketDepthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBinanceMarketDepthResponse.Merge(m, src)
}
func (m *GetBinanceMarketDepthResponse) XXX_Size() int {
	return xxx_messageInfo_GetBinanceMarketDepthResponse.Size(m)
}
func (m *GetBinanceMarketDepthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBinanceMarketDepthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBinanceMarketDepthResponse proto.InternalMessageInfo

func (m *GetBinanceMarketDepthResponse) GetLastUpdateId() int32 {
	if m != nil {
		return m.LastUpdateId
	}
	return 0
}

func (m *GetBinanceMarketDepthResponse) GetBids() []*Bids {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *GetBinanceMarketDepthResponse) GetAsks() []*Asks {
	if m != nil {
		return m.Asks
	}
	return nil
}

type GetBinanceMarketTradesRecentRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBinanceMarketTradesRecentRequest) Reset()         { *m = GetBinanceMarketTradesRecentRequest{} }
func (m *GetBinanceMarketTradesRecentRequest) String() string { return proto.CompactTextString(m) }
func (*GetBinanceMarketTradesRecentRequest) ProtoMessage()    {}
func (*GetBinanceMarketTradesRecentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec8c46fab743ea33, []int{4}
}

func (m *GetBinanceMarketTradesRecentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBinanceMarketTradesRecentRequest.Unmarshal(m, b)
}
func (m *GetBinanceMarketTradesRecentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBinanceMarketTradesRecentRequest.Marshal(b, m, deterministic)
}
func (m *GetBinanceMarketTradesRecentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBinanceMarketTradesRecentRequest.Merge(m, src)
}
func (m *GetBinanceMarketTradesRecentRequest) XXX_Size() int {
	return xxx_messageInfo_GetBinanceMarketTradesRecentRequest.Size(m)
}
func (m *GetBinanceMarketTradesRecentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBinanceMarketTradesRecentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBinanceMarketTradesRecentRequest proto.InternalMessageInfo

func (m *GetBinanceMarketTradesRecentRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetBinanceMarketTradesRecentRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type TradeInfo struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Price                string   `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string   `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	QuoteQuantity        string   `protobuf:"bytes,4,opt,name=quoteQuantity,proto3" json:"quoteQuantity,omitempty"`
	Time                 int64    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	IsBuyerMake          bool     `protobuf:"varint,6,opt,name=isBuyerMake,proto3" json:"isBuyerMake,omitempty"`
	IsBestMatch          bool     `protobuf:"varint,7,opt,name=isBestMatch,proto3" json:"isBestMatch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeInfo) Reset()         { *m = TradeInfo{} }
func (m *TradeInfo) String() string { return proto.CompactTextString(m) }
func (*TradeInfo) ProtoMessage()    {}
func (*TradeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec8c46fab743ea33, []int{5}
}

func (m *TradeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeInfo.Unmarshal(m, b)
}
func (m *TradeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeInfo.Marshal(b, m, deterministic)
}
func (m *TradeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeInfo.Merge(m, src)
}
func (m *TradeInfo) XXX_Size() int {
	return xxx_messageInfo_TradeInfo.Size(m)
}
func (m *TradeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TradeInfo proto.InternalMessageInfo

func (m *TradeInfo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TradeInfo) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *TradeInfo) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *TradeInfo) GetQuoteQuantity() string {
	if m != nil {
		return m.QuoteQuantity
	}
	return ""
}

func (m *TradeInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TradeInfo) GetIsBuyerMake() bool {
	if m != nil {
		return m.IsBuyerMake
	}
	return false
}

func (m *TradeInfo) GetIsBestMatch() bool {
	if m != nil {
		return m.IsBestMatch
	}
	return false
}

type GetBinanceMarketTradesRecentResponse struct {
	Results              []*TradeInfo `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetBinanceMarketTradesRecentResponse) Reset()         { *m = GetBinanceMarketTradesRecentResponse{} }
func (m *GetBinanceMarketTradesRecentResponse) String() string { return proto.CompactTextString(m) }
func (*GetBinanceMarketTradesRecentResponse) ProtoMessage()    {}
func (*GetBinanceMarketTradesRecentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec8c46fab743ea33, []int{6}
}

func (m *GetBinanceMarketTradesRecentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBinanceMarketTradesRecentResponse.Unmarshal(m, b)
}
func (m *GetBinanceMarketTradesRecentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBinanceMarketTradesRecentResponse.Marshal(b, m, deterministic)
}
func (m *GetBinanceMarketTradesRecentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBinanceMarketTradesRecentResponse.Merge(m, src)
}
func (m *GetBinanceMarketTradesRecentResponse) XXX_Size() int {
	return xxx_messageInfo_GetBinanceMarketTradesRecentResponse.Size(m)
}
func (m *GetBinanceMarketTradesRecentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBinanceMarketTradesRecentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBinanceMarketTradesRecentResponse proto.InternalMessageInfo

func (m *GetBinanceMarketTradesRecentResponse) GetResults() []*TradeInfo {
	if m != nil {
		return m.Results
	}
	return nil
}

type GetBinanceMarketTradesHistoricalRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	FromId               int64    `protobuf:"varint,3,opt,name=fromId,proto3" json:"fromId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBinanceMarketTradesHistoricalRequest) Reset() {
	*m = GetBinanceMarketTradesHistoricalRequest{}
}
func (m *GetBinanceMarketTradesHistoricalRequest) String() string { return proto.CompactTextString(m) }
func (*GetBinanceMarketTradesHistoricalRequest) ProtoMessage()    {}
func (*GetBinanceMarketTradesHistoricalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec8c46fab743ea33, []int{7}
}

func (m *GetBinanceMarketTradesHistoricalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBinanceMarketTradesHistoricalRequest.Unmarshal(m, b)
}
func (m *GetBinanceMarketTradesHistoricalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBinanceMarketTradesHistoricalRequest.Marshal(b, m, deterministic)
}
func (m *GetBinanceMarketTradesHistoricalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBinanceMarketTradesHistoricalRequest.Merge(m, src)
}
func (m *GetBinanceMarketTradesHistoricalRequest) XXX_Size() int {
	return xxx_messageInfo_GetBinanceMarketTradesHistoricalRequest.Size(m)
}
func (m *GetBinanceMarketTradesHistoricalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBinanceMarketTradesHistoricalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBinanceMarketTradesHistoricalRequest proto.InternalMessageInfo

func (m *GetBinanceMarketTradesHistoricalRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetBinanceMarketTradesHistoricalRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetBinanceMarketTradesHistoricalRequest) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

type GetBinanceMarketTradesHistoricalResponse struct {
	Results              []*TradeInfo `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetBinanceMarketTradesHistoricalResponse) Reset() {
	*m = GetBinanceMarketTradesHistoricalResponse{}
}
func (m *GetBinanceMarketTradesHistoricalResponse) String() string { return proto.CompactTextString(m) }
func (*GetBinanceMarketTradesHistoricalResponse) ProtoMessage()    {}
func (*GetBinanceMarketTradesHistoricalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec8c46fab743ea33, []int{8}
}

func (m *GetBinanceMarketTradesHistoricalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBinanceMarketTradesHistoricalResponse.Unmarshal(m, b)
}
func (m *GetBinanceMarketTradesHistoricalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBinanceMarketTradesHistoricalResponse.Marshal(b, m, deterministic)
}
func (m *GetBinanceMarketTradesHistoricalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBinanceMarketTradesHistoricalResponse.Merge(m, src)
}
func (m *GetBinanceMarketTradesHistoricalResponse) XXX_Size() int {
	return xxx_messageInfo_GetBinanceMarketTradesHistoricalResponse.Size(m)
}
func (m *GetBinanceMarketTradesHistoricalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBinanceMarketTradesHistoricalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBinanceMarketTradesHistoricalResponse proto.InternalMessageInfo

func (m *GetBinanceMarketTradesHistoricalResponse) GetResults() []*TradeInfo {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBinanceMarketDepthRequest)(nil), "api.binance.GetBinanceMarketDepthRequest")
	proto.RegisterType((*Asks)(nil), "api.binance.Asks")
	proto.RegisterType((*Bids)(nil), "api.binance.Bids")
	proto.RegisterType((*GetBinanceMarketDepthResponse)(nil), "api.binance.GetBinanceMarketDepthResponse")
	proto.RegisterType((*GetBinanceMarketTradesRecentRequest)(nil), "api.binance.GetBinanceMarketTradesRecentRequest")
	proto.RegisterType((*TradeInfo)(nil), "api.binance.TradeInfo")
	proto.RegisterType((*GetBinanceMarketTradesRecentResponse)(nil), "api.binance.GetBinanceMarketTradesRecentResponse")
	proto.RegisterType((*GetBinanceMarketTradesHistoricalRequest)(nil), "api.binance.GetBinanceMarketTradesHistoricalRequest")
	proto.RegisterType((*GetBinanceMarketTradesHistoricalResponse)(nil), "api.binance.GetBinanceMarketTradesHistoricalResponse")
}

func init() { proto.RegisterFile("api/binance/market.proto", fileDescriptor_ec8c46fab743ea33) }

var fileDescriptor_ec8c46fab743ea33 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x51, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xbf, 0x8d, 0x93, 0xb4, 0x99, 0x7c, 0x20, 0xba, 0x82, 0x6a, 0x15, 0x81, 0x64, 0x99,
	0x22, 0x0c, 0x42, 0x69, 0x29, 0x70, 0x00, 0xa2, 0x48, 0xd4, 0x52, 0xf3, 0xc0, 0x02, 0x12, 0x0f,
	0xbc, 0x6c, 0xec, 0x2d, 0x59, 0xc5, 0xf6, 0x3a, 0xde, 0xb1, 0x50, 0x0e, 0xc0, 0x01, 0x7a, 0x04,
	0xce, 0xc3, 0xa5, 0x90, 0x37, 0x4e, 0x14, 0xd3, 0x90, 0xa6, 0x79, 0xdb, 0x99, 0xf9, 0xcd, 0x78,
	0xf6, 0x3f, 0xe3, 0x05, 0x26, 0x32, 0x75, 0x3a, 0x56, 0xa9, 0x48, 0x43, 0x79, 0x9a, 0x88, 0x7c,
	0x2a, 0xb1, 0x9f, 0xe5, 0x1a, 0x35, 0xed, 0x8a, 0x4c, 0xf5, 0xab, 0x88, 0x77, 0x09, 0x8f, 0x3f,
	0x48, 0x1c, 0x2c, 0xac, 0x91, 0xc5, 0x86, 0x32, 0xc3, 0x09, 0x97, 0xb3, 0x42, 0x1a, 0xa4, 0xc7,
	0xd0, 0x36, 0xf3, 0x64, 0xac, 0x63, 0x46, 0x5c, 0xe2, 0x77, 0x78, 0x65, 0xd1, 0x87, 0xd0, 0x8a,
	0x55, 0xa2, 0x90, 0x35, 0x5c, 0xe2, 0xb7, 0xf8, 0xc2, 0xf0, 0x5e, 0x41, 0xf3, 0xbd, 0x99, 0x1a,
	0xfa, 0x00, 0x9c, 0x4b, 0xfd, 0xa3, 0x4a, 0x29, 0x8f, 0x94, 0x42, 0xf3, 0x42, 0x7d, 0x9f, 0x58,
	0xbc, 0xc3, 0xed, 0xb9, 0xa4, 0x07, 0x2a, 0xda, 0x95, 0xbe, 0x26, 0xf0, 0xe4, 0x1f, 0xad, 0x9a,
	0x4c, 0xa7, 0x46, 0x52, 0x0f, 0xfe, 0x8f, 0x85, 0xc1, 0x2f, 0x59, 0x24, 0x50, 0x06, 0x91, 0x2d,
	0xd8, 0xe2, 0x35, 0x1f, 0x7d, 0x06, 0xcd, 0xb1, 0x8a, 0x0c, 0x6b, 0xb8, 0x8e, 0xdf, 0x3d, 0x3f,
	0xea, 0xaf, 0x69, 0xd1, 0x2f, 0x9b, 0xe1, 0x36, 0x5c, 0x62, 0xc2, 0x4c, 0x0d, 0x73, 0x36, 0x60,
	0xe5, 0x0d, 0xb9, 0x0d, 0x7b, 0x9f, 0xe0, 0xe9, 0xdf, 0x2d, 0x7d, 0xce, 0x45, 0x24, 0x0d, 0x97,
	0xa1, 0x4c, 0x71, 0x3f, 0x11, 0x7f, 0x13, 0xe8, 0xd8, 0x2a, 0x41, 0x7a, 0xa5, 0xe9, 0x7d, 0x68,
	0x04, 0xc3, 0xea, 0x2a, 0x8d, 0x60, 0x58, 0xe6, 0x64, 0xb9, 0x0a, 0x65, 0xa5, 0xcd, 0xc2, 0xa0,
	0x3d, 0x38, 0x9c, 0x15, 0x22, 0x45, 0x85, 0x73, 0xe6, 0xd8, 0xc0, 0xca, 0xa6, 0x27, 0x70, 0x6f,
	0x56, 0x68, 0x94, 0x1f, 0x97, 0x40, 0xd3, 0x02, 0x75, 0x67, 0x29, 0x39, 0xaa, 0x44, 0xb2, 0x96,
	0x4b, 0x7c, 0x87, 0xdb, 0x33, 0x75, 0xa1, 0xab, 0xcc, 0xa0, 0x98, 0xcb, 0x7c, 0x24, 0xa6, 0x92,
	0xb5, 0x5d, 0xe2, 0x1f, 0xf2, 0x75, 0x57, 0x45, 0x48, 0x83, 0x23, 0x81, 0xe1, 0x84, 0x1d, 0xac,
	0x88, 0xa5, 0xcb, 0xfb, 0x0a, 0x27, 0xdb, 0x25, 0xaa, 0x86, 0x77, 0x06, 0x07, 0xb9, 0x34, 0x45,
	0x8c, 0x86, 0x11, 0x2b, 0xfa, 0x71, 0x4d, 0xf4, 0x95, 0x20, 0x7c, 0x89, 0x79, 0x1a, 0x9e, 0x6f,
	0xae, 0x7c, 0xa1, 0x0c, 0xea, 0x5c, 0x85, 0x22, 0xde, 0x6b, 0x00, 0x25, 0x7d, 0x95, 0xeb, 0x24,
	0x88, 0xac, 0x94, 0x0e, 0xaf, 0x2c, 0xef, 0x1b, 0xf8, 0xb7, 0x7f, 0x70, 0xdf, 0xeb, 0x9c, 0xff,
	0x72, 0xe0, 0xa8, 0xbe, 0xdc, 0x02, 0x05, 0xcd, 0xe0, 0xd1, 0xc6, 0xa5, 0xa7, 0x2f, 0x6a, 0xf5,
	0xb6, 0xfd, 0xc3, 0xbd, 0x97, 0xbb, 0xa0, 0x8b, 0xbe, 0xbd, 0xff, 0xe8, 0x4f, 0x72, 0xf3, 0x49,
	0x58, 0x9f, 0x18, 0x3d, 0xdb, 0x5a, 0x6e, 0xc3, 0xfe, 0xf7, 0x5e, 0xdf, 0x21, 0x63, 0xd5, 0xc7,
	0x35, 0x01, 0xf7, 0x36, 0xb9, 0xe9, 0xdb, 0x1d, 0x2a, 0xdf, 0x58, 0x87, 0xde, 0xbb, 0x3b, 0x66,
	0x2d, 0x7b, 0x1a, 0xb7, 0xed, 0x0b, 0xfa, 0xe6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xae,
	0x04, 0x20, 0x5d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BinanceMarketDataClient is the client API for BinanceMarketData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BinanceMarketDataClient interface {
	GetBinanceMarketDepth(ctx context.Context, in *GetBinanceMarketDepthRequest, opts ...grpc.CallOption) (*GetBinanceMarketDepthResponse, error)
	GetBinanceMarketTradesRecent(ctx context.Context, in *GetBinanceMarketTradesRecentRequest, opts ...grpc.CallOption) (*GetBinanceMarketTradesRecentResponse, error)
	GetBinanceMarketTradesHistorical(ctx context.Context, in *GetBinanceMarketTradesHistoricalRequest, opts ...grpc.CallOption) (*GetBinanceMarketTradesHistoricalResponse, error)
}

type binanceMarketDataClient struct {
	cc *grpc.ClientConn
}

func NewBinanceMarketDataClient(cc *grpc.ClientConn) BinanceMarketDataClient {
	return &binanceMarketDataClient{cc}
}

func (c *binanceMarketDataClient) GetBinanceMarketDepth(ctx context.Context, in *GetBinanceMarketDepthRequest, opts ...grpc.CallOption) (*GetBinanceMarketDepthResponse, error) {
	out := new(GetBinanceMarketDepthResponse)
	err := c.cc.Invoke(ctx, "/api.binance.BinanceMarketData/GetBinanceMarketDepth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binanceMarketDataClient) GetBinanceMarketTradesRecent(ctx context.Context, in *GetBinanceMarketTradesRecentRequest, opts ...grpc.CallOption) (*GetBinanceMarketTradesRecentResponse, error) {
	out := new(GetBinanceMarketTradesRecentResponse)
	err := c.cc.Invoke(ctx, "/api.binance.BinanceMarketData/GetBinanceMarketTradesRecent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binanceMarketDataClient) GetBinanceMarketTradesHistorical(ctx context.Context, in *GetBinanceMarketTradesHistoricalRequest, opts ...grpc.CallOption) (*GetBinanceMarketTradesHistoricalResponse, error) {
	out := new(GetBinanceMarketTradesHistoricalResponse)
	err := c.cc.Invoke(ctx, "/api.binance.BinanceMarketData/GetBinanceMarketTradesHistorical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BinanceMarketDataServer is the server API for BinanceMarketData service.
type BinanceMarketDataServer interface {
	GetBinanceMarketDepth(context.Context, *GetBinanceMarketDepthRequest) (*GetBinanceMarketDepthResponse, error)
	GetBinanceMarketTradesRecent(context.Context, *GetBinanceMarketTradesRecentRequest) (*GetBinanceMarketTradesRecentResponse, error)
	GetBinanceMarketTradesHistorical(context.Context, *GetBinanceMarketTradesHistoricalRequest) (*GetBinanceMarketTradesHistoricalResponse, error)
}

// UnimplementedBinanceMarketDataServer can be embedded to have forward compatible implementations.
type UnimplementedBinanceMarketDataServer struct {
}

func (*UnimplementedBinanceMarketDataServer) GetBinanceMarketDepth(ctx context.Context, req *GetBinanceMarketDepthRequest) (*GetBinanceMarketDepthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBinanceMarketDepth not implemented")
}
func (*UnimplementedBinanceMarketDataServer) GetBinanceMarketTradesRecent(ctx context.Context, req *GetBinanceMarketTradesRecentRequest) (*GetBinanceMarketTradesRecentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBinanceMarketTradesRecent not implemented")
}
func (*UnimplementedBinanceMarketDataServer) GetBinanceMarketTradesHistorical(ctx context.Context, req *GetBinanceMarketTradesHistoricalRequest) (*GetBinanceMarketTradesHistoricalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBinanceMarketTradesHistorical not implemented")
}

func RegisterBinanceMarketDataServer(s *grpc.Server, srv BinanceMarketDataServer) {
	s.RegisterService(&_BinanceMarketData_serviceDesc, srv)
}

func _BinanceMarketData_GetBinanceMarketDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBinanceMarketDepthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinanceMarketDataServer).GetBinanceMarketDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.binance.BinanceMarketData/GetBinanceMarketDepth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinanceMarketDataServer).GetBinanceMarketDepth(ctx, req.(*GetBinanceMarketDepthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinanceMarketData_GetBinanceMarketTradesRecent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBinanceMarketTradesRecentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinanceMarketDataServer).GetBinanceMarketTradesRecent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.binance.BinanceMarketData/GetBinanceMarketTradesRecent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinanceMarketDataServer).GetBinanceMarketTradesRecent(ctx, req.(*GetBinanceMarketTradesRecentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinanceMarketData_GetBinanceMarketTradesHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBinanceMarketTradesHistoricalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinanceMarketDataServer).GetBinanceMarketTradesHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.binance.BinanceMarketData/GetBinanceMarketTradesHistorical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinanceMarketDataServer).GetBinanceMarketTradesHistorical(ctx, req.(*GetBinanceMarketTradesHistoricalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BinanceMarketData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.binance.BinanceMarketData",
	HandlerType: (*BinanceMarketDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBinanceMarketDepth",
			Handler:    _BinanceMarketData_GetBinanceMarketDepth_Handler,
		},
		{
			MethodName: "GetBinanceMarketTradesRecent",
			Handler:    _BinanceMarketData_GetBinanceMarketTradesRecent_Handler,
		},
		{
			MethodName: "GetBinanceMarketTradesHistorical",
			Handler:    _BinanceMarketData_GetBinanceMarketTradesHistorical_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/binance/market.proto",
}
