// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/coinbase/accounts.proto

package api_coinbase

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Balance struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31380befcbcb350, []int{0}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Balance) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Primary              bool     `protobuf:"varint,3,opt,name=primary,proto3" json:"primary,omitempty"`
	Currency             string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance              *Balance `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ResourcePath         string   `protobuf:"bytes,8,opt,name=resource_path,json=resourcePath,proto3" json:"resource_path,omitempty"`
	Ready                bool     `protobuf:"varint,9,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31380befcbcb350, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

func (m *Account) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Account) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *Account) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Account) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Account) GetResourcePath() string {
	if m != nil {
		return m.ResourcePath
	}
	return ""
}

func (m *Account) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

type ListAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31380befcbcb350, []int{2}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

type ListAccountsResponse struct {
	Data                 []*Account `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31380befcbcb350, []int{3}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetData() []*Account {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31380befcbcb350, []int{4}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateAccountResponse struct {
	Data                 *Account `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountResponse) Reset()         { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()    {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31380befcbcb350, []int{5}
}

func (m *UpdateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountResponse.Unmarshal(m, b)
}
func (m *UpdateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountResponse.Merge(m, src)
}
func (m *UpdateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountResponse.Size(m)
}
func (m *UpdateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountResponse proto.InternalMessageInfo

func (m *UpdateAccountResponse) GetData() *Account {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Balance)(nil), "api.coinbase.Balance")
	proto.RegisterType((*Account)(nil), "api.coinbase.Account")
	proto.RegisterType((*ListAccountsRequest)(nil), "api.coinbase.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "api.coinbase.ListAccountsResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "api.coinbase.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "api.coinbase.UpdateAccountResponse")
}

func init() { proto.RegisterFile("api/coinbase/accounts.proto", fileDescriptor_e31380befcbcb350) }

var fileDescriptor_e31380befcbcb350 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0xd2, 0x8f, 0xb4, 0x47, 0x61, 0x30, 0x2d, 0xb2, 0x40, 0x48, 0x51, 0x58, 0xca, 0x92,
	0x4a, 0xb0, 0x21, 0x31, 0xa4, 0x33, 0x03, 0x8a, 0xc4, 0x5c, 0x5d, 0x9d, 0x93, 0x6a, 0x89, 0x26,
	0xc6, 0x76, 0x86, 0xfe, 0x08, 0xfe, 0x33, 0xaa, 0x63, 0x23, 0x42, 0x07, 0xd8, 0xf2, 0x3e, 0xee,
	0x9e, 0xdf, 0x29, 0x70, 0x83, 0x4a, 0xae, 0x44, 0x23, 0xeb, 0x2d, 0x1a, 0x5a, 0xa1, 0x10, 0x4d,
	0x5b, 0x5b, 0x93, 0x2b, 0xdd, 0xd8, 0x86, 0xcd, 0x50, 0xc9, 0x3c, 0x88, 0xd9, 0x33, 0x24, 0x6b,
	0x7c, 0xc7, 0x5a, 0x10, 0xbb, 0x82, 0x31, 0xee, 0x8f, 0x4e, 0x1e, 0xa5, 0xd1, 0x72, 0x5a, 0x7a,
	0xc4, 0xae, 0x61, 0x22, 0x5a, 0xad, 0xa9, 0x16, 0x07, 0x1e, 0x3b, 0xe5, 0x1b, 0x67, 0x9f, 0x31,
	0x24, 0x45, 0xb7, 0x9f, 0x5d, 0x40, 0x2c, 0x2b, 0x3f, 0x1b, 0xcb, 0x8a, 0x31, 0x18, 0xd6, 0xb8,
	0x27, 0x3f, 0xe3, 0xbe, 0x19, 0x87, 0x44, 0x69, 0xb9, 0x47, 0x7d, 0xe0, 0x83, 0x34, 0x5a, 0x4e,
	0xca, 0x00, 0x7b, 0x29, 0xc3, 0x7e, 0x0a, 0x5b, 0x41, 0xb2, 0xed, 0x1e, 0xc9, 0x47, 0x69, 0xb4,
	0x3c, 0x7b, 0x58, 0xe4, 0x3f, 0x4b, 0xe4, 0xbe, 0x41, 0x19, 0x5c, 0xec, 0x16, 0x40, 0x68, 0x42,
	0x4b, 0xd5, 0x06, 0x2d, 0x1f, 0xbb, 0x75, 0x53, 0xcf, 0x14, 0xf6, 0x28, 0xb7, 0xaa, 0x0a, 0x72,
	0xd2, 0xc9, 0x9e, 0x29, 0x2c, 0xbb, 0x83, 0x73, 0x4d, 0xa6, 0x69, 0xb5, 0xa0, 0x8d, 0x42, 0xbb,
	0xe3, 0x13, 0xe7, 0x98, 0x05, 0xf2, 0x15, 0xed, 0x8e, 0xcd, 0x61, 0xa4, 0x09, 0xab, 0x03, 0x9f,
	0xba, 0x1e, 0x1d, 0xc8, 0x16, 0x70, 0xf9, 0x22, 0x8d, 0xf5, 0x27, 0x31, 0x25, 0x7d, 0xb4, 0x64,
	0x6c, 0x56, 0xc0, 0xbc, 0x4f, 0x1b, 0xd5, 0xd4, 0x86, 0xd8, 0x3d, 0x0c, 0x2b, 0xb4, 0xc8, 0xa3,
	0x74, 0x70, 0xda, 0xca, 0xbb, 0x4b, 0x67, 0xc9, 0x9e, 0x60, 0xfe, 0xe6, 0x5e, 0x18, 0xe8, 0x6e,
	0xf5, 0x7f, 0xae, 0x9e, 0xad, 0x61, 0xf1, 0x6b, 0xf6, 0x24, 0x3f, 0xfa, 0x23, 0x7f, 0x3b, 0x76,
	0x7f, 0xcf, 0xe3, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x64, 0x96, 0x4b, 0x5c, 0x02, 0x00,
	0x00,
}
