name: CryptoTraderWorkflow
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Install Protoc
      uses: Arduino/actions/setup-protoc@master
      with:
        version: '3.x'

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: test
      run: make test-build

    - name: Build
      run: make build-all
